### ISSUE TITLE
试用领取通知报错

### ISSUE THREAD

**Issue by xiaoyouke01** [Hyper-Beast/JD_Scripts#1]
更新之前不报错，更新后出现问题
读取auth.json文件出错，跳过获取备注
Traceback (most recent call last):
  File "raw_main_jd_try_notify.py", line 138, in <module>
    if remarkinfos[ptpin]!='':
KeyError: 'xiaoyouke_m'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "raw_main_jd_try_notify.py", line 143, in <module>
    printf(e.value)
AttributeError: 'KeyError' object has no attribute 'value'

## 执行结束... 2022-01-06 10:43:04 耗时 2 秒

**Comment by Hyper-Beast** [comment]
> 更新之前不报错，更新后出现问题 读取auth.json文件出错，跳过获取备注 Traceback (most recent call last): File "raw_main_jd_try_notify.py", line 138, in if remarkinfos[ptpin]!='': KeyError: 'xiaoyouke_m'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "raw_main_jd_try_notify.py", line 143, in printf(e.value) AttributeError: 'KeyError' object has no attribute 'value'
> 
> ## 执行结束... 2022-01-06 10:43:04 耗时 2 秒

青龙版本多少，高的我没测试2.10.0或者以下的应该没问题，版本太高应该是获取不到备注但是不影响使用，脚本你更新下就可以了，前面错误处理写错了刚才改了

**Comment by xiaoyouke01** [comment]
青龙版本是2.10.13

**Comment by Hyper-Beast** [comment]
> 青龙版本是2.10.13

2.10.13脚本路径不一样了，你可以自己改下69行，或者不改就现在这样用，只是不显示备注而已
