### ISSUE TITLE
读取auth.json文件出错

### ISSUE THREAD

**Issue by Mr-Coffee666** [Hyper-Beast/JD_Scripts#3]
运行脚本，提示
xxxxxxxxxxxx
读取auth.json文件出错，跳过获取备注
请问这个auth.json文件如何生成？

**Comment by Hyper-Beast** [comment]
> 运行脚本，提示 xxxxxxxxxxxx 读取auth.json文件出错，跳过获取备注 请问这个auth.json文件如何生成？

青龙面板的，我这个路径是2.9到2.10.0版本用的，高版本我不知道放在哪里

**Comment by Hyper-Beast** [comment]
已解决
