### ISSUE TITLE
未识别到待领取

### ISSUE THREAD

**Issue by Mr-Coffee666** [Hyper-Beast/JD_Scripts#5]
![image](https://user-images.githubusercontent.com/66343425/155257470-66badd69-3f11-4047-a958-9bc8e7142ba1.png)

**Comment by Hyper-Beast** [comment]
> ![image](https://user-images.githubusercontent.com/66343425/155257470-66badd69-3f11-4047-a958-9bc8e7142ba1.png)

更新了，你再试试？
